---
# tasks file for php
- name: "Instala o PHP do Debian"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: 
      - php7.3 
      - php7.3-fpm 
      - php7.3-cli 
      - php7.3-common 
      - php7.3-curl 
      - php7.3-mbstring 
      - php7.3-mysql 
      - php7.3-xml 
      - php7.3-gd 
      - php7.3-exif
    state: latest
  when: (ansible_facts['os_family'] == "Debian")

- name: Enable EPEL Repository on CentOS 7
  yum:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: enable epel
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: enable epel 2
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: enable yum-utils
  shell:
    cmd: "yum-config-manager --enable remi-php74"
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: "Instala o PHP do RedHat"
  yum:
    name:
      - php
      - php-mysql
      - php-mysqlnd
      - php-cli
    state: present
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - ReiniciaHttpd