---
- hosts: all
  become: yes
  gather_facts: yes

  vars:
    default_dir: /opt/custom
    teste: "{{ default_dir }}/script"
    dict_dir: {
      scripts: "{{ default_dir }}/bin",
      backup: "{{ default_dir }}/backup",
      log: "{{ default_dir }}/log",
      temp: "{{ default_dir }}/temp",
    }

  tasks:
  - name: "INSTALA PACOTE WGET CENTOS"
    yum:
      update_cache: yes
      name: "wget"
      state: present
    when: (ansible_facts['distribution'] == "CentOS")

  - name: "DEFINE HOSTNAME SERVIDORES"
    hostname:
      name: "{{ hostname }}"

  - name: "CRIA DIRETORIO PADRAO NOS SERVIDORES"
    file:
      path: "{{ item }}"
      owner: mario
      group: mario
      state: directory
    with_items:
    - "{{ dict_dir.scripts}}"
    - "{{ dict_dir.backup}}"
    - "{{ dict_dir.log}}"
    - "{{ dict_dir.temp}}"    

  - name: "CRIA ARQUIVO SIMPLES"
    file:
      path: "{{ default_dir }}/teste.py"
      state: touch
      owner: mario
      group: mario
      mode: 0755
      modification_time: preserve
      access_time: preserve

  - name: "exemplo de debug"
    debug:
      msg: "{{ dict_dir.scripts }}"

  - name: "EXEMPLO DE REGISTER"
    shell: "date -u"
    register: linux_date

  - name: "EXIBINDO REGISTER"
    debug:
      msg: "{{ linux_date.start }}"

