---
- name: "Instala o Apache em distro derivadas do Debian"
  apt:
    name: 
      - apache2
      - libapache2-mod-fcgid
      - libapache2-mod-security2
      - libapache2-mod-evasive
      - openssl
    state: latest
  when: (ansible_facts['os_family'] == "Debian")
  notify:
    - enableApache2

- name: "Habilita mods no apache2 - Debian"
  apache2_module:
    name: "{{ item }}"
  with_items:
    - actions 
    - fcgid 
    - alias 
    - proxy_fcgi
    - headers
    - ssl
  when: (ansible_facts['os_family'] == "Debian")

- name: "Cria virtual host com as configurações do site - debian" 
  template:
    src: templates/site.conf
    dest: /etc/apache2/sites-available/{{ log_prefix }}.conf
  when: (ansible_facts['os_family'] == "Debian")
  notify:
    - enableSite
    - reloadApache2
    - addInHostsFile
    - InstallWordPress
    - SetPermissionWP-Debian